README.md
client/app/page.js
client/app/socketClient.js
client/package-lock.json
client/package.json
server/config/config.js
server/package-lock.json
server/package.json
server/server.js
server/socketServer.js

Players can now connect to custom rooms using sockets and send custom messages.
This will be form the basis of how they interact with each other in Jeopardy game rooms later on.
Added in new files to both client and server side that handle socket logic.
Rooms can be created in the developer console. User interactivity for this will be added later.
Manually tested to make sure socket connections open and with multiple tabs to make messages were sent between rooms correctly.

socket rooms now working

---

client/app/ReduxProvider.js
client/app/game-board/game-board.module.css
client/app/game-board/page.js
client/app/game-search-page/game-search.module.css
client/app/game-search-page/page.js
client/app/layout.js
client/app/page.js
client/app/redux/data.js
client/app/redux/store.js
client/package-lock.json
client/package.json
server/controllers/jeopardy.js
server/seeders/20240925213052-demo_jeopardies.js2.js

Reverts csci-499-fa24/Team2#72
Seeing if the render deploy now works -- VERIFY BEFORE MERGING

Revert "Revert "API/Game Board Functionality""

---

client/app/game-board/page.js
client/app/game-search-page/page.js

- Added game-search-page to get all show numbers, which routes to game board
- Added API functionality to get info from the database, removes any duplicate questions to avoid creation of extra boxes
- Added game board functionality: info from database is implemented into the game board and when you click on a box, pop up with the content (question, your answer field, submit/close button) will appear

Debugging deployment errors: accounted for case where no data is selected

---

client/app/[userid]/page.js
client/app/game-board/page.js
client/app/game-search-page/page.js
client/app/page.js
client/app/socketClient.js
client/package-lock.json
server/server.js
server/socketServer.js

Sockets are persistent meaning that if you change the route, the connection will re-establish.
Display name can be set for rooms.
A function exists for retrieving all the rooms and users inside.
If user goes from '/' to '/game-board', client will reconnect. But connection will die if client exits out or goes back to '/'.
Use setDisplayName() to set name and you must do it before setRoomKey() or it will throw an error.
Use getRooms() to get all the rooms and players inside.  
Manually tested to make sure that the socket connections are open. Made sure that sendMessage() communication is still working after changes.

socket persistence, display names, retrieving rooms, all implemented

---

server/models/jeopardy_questions.js
server/server.js

This pull request introduces several new features and enhancements to the application, focusing primarily on game management functionality, Jeopardy! round validation, and category handling. These changes are aimed at improving the app’s game flow logic and its API endpoints, while also fixing some minor bugs.
- **Feature implementation**: We’ve added multiple game-related features, including generating unique game IDs, validating game data for different rounds, managing game state across Jeopardy! and Double Jeopardy! rounds, and handling expired games.
- **Motivation**: The changes ensure that the game logic follows Jeopardy!’s standard format with six categories and five questions per category, and that games are properly validated and managed to prevent data inconsistencies.
The …

Server Game Management: Functions & API Endpoints

---

client/app/[userid]/page.js
server/controllers/index.js

This PR refactors how routes are imported and used within the `server.js` file to restore the functionality of game-related routes (`gameRoutes`) and ensure compatibility with other controllers. Previously, the `gameRoutes` were not functioning correctly due to changes in how the routes were dealt with. This update organizes the routing structure and restores full API functionality.
- What feature, bug fix, or enhancement is being implemented?
- Refactoring and reorganization of the Express route structure to properly integrate multiple route files, including `gameRoutes`.
- Why is this change necessary?
- To resolve issues with the `gameRoutes` API not working and to allow for a scalable routing system that can support additional controllers.
- Verifying that `gameRoutes` and other …

Attempted fix for the game api

---

client/app/socketClient.js

Changing socket connection URL.
Quick fix changing localhost:8080 to https://team2-server.onrender.com/ for socket connection URL.
Not really applicable for this.

fixed socket connection url

---

client/app/game-board/game-board.module.css
client/app/game-board/page.js
client/app/socketClient.js

- daily doubles implemented
- fixed error with bypass method not working
- [ x ] daily double allows for wagering and blocking other users from answering
- [ x ] fixed bypass method in socketClient.js
Describe how the changes were tested. If possible, include:
- tested locally, with both user page and bypass method reaching the gameboard
- made sure all cases of daily double works and all players see the screen

Implemented daily doubles

---

client/app/game-board/game-board.module.css
client/app/game-board/page.js
client/app/socketClient.js
client/app/waiting-room/[roomid]/page.js

- issue with user not being able to join game board from waiting room fixed
- [ x ] issue fixed by forcing setRoomKey() to run after an asynchronous call of setDisplayName() 
- manually tested through multiple entry ways to make sure this method doesn't break anything

fixed issue with unable to join from waiting room

---

server/controllers/history.js
server/lib/gameUtils.js

This pull request introduces functionality for recording the outcome of a game. It allows the application to store game results in the database when a game ends, ensuring accurate tracking of player history and game statistics.
- Implemented a new route to handle game termination requests.
- Integrated the `endGame` function to record game details in the `game_history` table.
- Added functionality to log each player's performance in the `player_history` table.
This change is necessary to maintain a reliable record of game outcomes, which enhances the user experience by providing insights into player performance and game history. 
The following testing procedures were followed to ensure the changes function as intended:
- **Unit Tests**: Added unit tests for the `endGame` function to …

Added game utils function for recording the game for user

---

client/app/[userid]/[userid].module.css
client/app/[userid]/page.js
server/config/config.js
server/controllers/games.js

- Updated the dashboard with new room creation and joining features
- Added a popup for "Create New Room" button, with options for a private room toggle and max players (4-8)
- Max players now displayed for each room
- Created a "Join Game" button that triggers a popup for inputting a room key to join both public and private rooms
- Updated the "Available Rooms" box to display only public games, excluding private or in-progress rooms 
- Tested/viewed changes locally

Updated Dashboard

---

client/app/waiting-room/[roomid]/page.js

Removed reinforcement for number of players to allow game start. For ease of demo but will be added back later on
N/A

No Minimum Players

---

client/app/game-board/page.js

Change to the game-board page.js where after Final Jeopardy players will route to a endGame function
Added a function that would essentially determine the winner and send an system alert to all players. After this it will route the user back to the homepage (game-search-page in your files).
It also records the game and ends the game using record_game & end-game api endpoints
Added correct api endpoints to record game data and end game

Redirects to home after a win & alerts players

---

client/app/game-board/game-board.module.css
client/app/game-board/page.js
client/app/socketClient.js

Players now have turns on when they can select a clue. At first it is randomly chosen, then it becomes whoever answered the last clue correctly. Before, everyone could select at the same time, causing chaos. 
Describe how the changes were tested. If possible, include:
- Manual testing with different clients in the same room interacting with the same game board
- Many edge cases tested in order to make sure features did not break game mechanics

added player turns

---

client/app/layout.js
client/app/page.js

Updates to fix the merges from code clean-up. 
Please make sure there are no errors for imports when testing.

Remove redux provider import

---

client/app/[userid]/[userid].module.css
client/app/[userid]/page.js
client/app/[userid]/profile/page.js
client/app/[userid]/profile/profile.module.css
client/app/game-search-page/page.js
client/app/socketClient.js
client/package-lock.json
client/package.json

Updated visuals for profile page 
- Added tabs for profile page: profile, history, and stats
- Updated styling for "Past Games"
- Used dummy data in json like format to create dummy charts 
- Added a display for total wins, total losses, and win rate

Updated Profile Page

---

client/app/waiting-room/[roomid]/page.js
client/app/waiting-room/waiting-page.module.css
client/package-lock.json
client/package.json

Previously there were conflicts in styling that rendered the `show Rules` text to not toggle the instructions. With the modification, the rule box should show up seamlessly.
Make sure you do an `npm i` in the `./client` and just make sure everything is clickable in the waiting room page (ready button, show Rules, and x icon on the rule box`

Show Rules Styling Updates

---

server/tests/index.test.js
server/tests/socketHandler.test.js

Test coverage improvements for the server with a focus on the the socketServer and some other files.
N/A

Jest test coverage

---

client/app/waiting-room/[roomid]/page.js

Users ready statuses are shown and updated in real time. Users are also redirected to the game-search-page once the last non-ready user in the room toggles the ready button.
Please test on two accounts and ensure both players are able to toggle ready and not ready. Once the second user toggles ready in the room with two players, it should route them both to the gameboard after the game-search-page.
NOTE: **BUGS NOTICIED TO BE DEBUGGED IN ANOTHER PR**
- There seems to be two "next round" buttons on the game board page
- The users seem to have no money displayed upon the start of the game (0 isn't displayed)
- The second user doesn't get a turn. Only the first player is allowed to …

sectioned useEffect and resolved bug with removed ready status and routes users to the gameboard

---

server/tests/gameUtils.test.js

Added partial test coverage for gameUtils.js
Describe how the changes were tested. If possible, include:
- ran the jest test to see the suite i wrote passing

added some coverage for gameUtils

---

client/app/[userid]/page.js
client/app/waiting-room/[roomid]/page.js
client/package-lock.json
server/controllers/index.js
server/socketServer.js

Rewriting logic for available rooms list to prevent users from joining a room that is in game
- Prevent users from joining a room that has started a game
Tested changes locally with 3 accounts

(New) Updated Available Rooms 

---

server/tests/games.test.js

Added test coverage for games.js, was able to get it to 100% 
- Finished the test coverage for games.js
Tested test coverage locally

Added test coverage for games.js

---

server/tests/gameUtils.test.js
server/tests/history.test.js
server/tests/jeopardy.test.js
server/tests/socketHandler.test.js

Added tests for history.js and jeopardy.js
- Wrote tests for history.js to get the coverage to 100%
- Added more tests for jeopardy.js to get the coverage from 62% to 100%
Tested locally through npm test

Added test coverage for history.js and jeopardy.js

---

client/app/game-board/page.js
client/app/game-board/voiceChatClient.js
client/package-lock.json
client/package.json
server/server.js
server/voiceChatServer.js

Implemented voice chat on the game board.
- [ x ] voice chat added, players are automatically connected once they reach the game board, but they have to set status first. to set status, they must set the role variable in local storage to either initiator or responder
Describe how the changes were tested. If possible, include:
- tested locally. unfortunately with features like this, there has to be testing in deployment as well, to make sure local things work in deployment. we had issues last time with sockets in deployment and it took several deployments to get it all working

implemented voice chat

---

client/app/game-board/page.js
client/app/game-board/voiceChatClient.js
client/app/waiting-room/[roomid]/page.js
client/app/waiting-room/[roomid]/voiceChatClient.js
client/package-lock.json
client/package.json
server/server.js
server/tests/voiceChat.test.js
server/voiceChatServer.js

Implemented voice chat on the game board. Fixed some port issues we were having with deployment
- voice chat added, players are automatically connected once they reach the game board, but they have to set status first. to set status, they must set the role variable in local storage to either initiator or responder
tested locally. unfortunately with features like this, there has to be testing in deployment as well, to make sure local things work in deployment. we had issues last time with sockets in deployment and it took several deployments to get it all working.
note: this time we are testing with the specific PR deployment link to make sure it works

fixing port issue with voice chat
